import type { LangContent, LangId } from "./types";

export const LANG_ORDER: LangId[] = ["yue", "cmn", "jpn"];
export const TABS = ["Home", "Converse", "Vocabulary", "Reading", "Practice", "Progress"];
export const GOAL_TARGET = 15; // minutes
export const VOCAB_DECKS = ["Greetings", "Food & drink", "Daily life"];

export const CONTENT: Record<LangId, LangContent> = {
  cmn: {
    id: "cmn",
    pill: "普",
    name: "Mandarin",
    speechLang: "zh-CN",
    romanSystem: "Pinyin",
    greeting: { glyph: "早安", roman: "zǎo ān", meaning: "good morning" },
    hero: {
      id: "cmn-tea",
      glyph: "茶",
      roman: "chá",
      meaning: "tea",
      anchor: "🍵",
      example: { glyph: "喝茶", roman: "hē chá", gloss: "to drink tea" },
    },
    review: [
      { id: "ni-hao", glyph: "你好", roman: "nǐ hǎo", meaning: "hello", anchor: "👋",
        example: { glyph: "你好吗", roman: "nǐ hǎo ma", gloss: "how are you?" } },
      { id: "xiexie", glyph: "谢谢", roman: "xiè xie", meaning: "thank you", anchor: "🙏",
        example: { glyph: "谢谢你", roman: "xiè xie nǐ", gloss: "thank you" } },
      { id: "chifan", glyph: "吃饭", roman: "chī fàn", meaning: "to eat a meal", anchor: "🍚",
        example: { glyph: "吃饭了吗", roman: "chī fàn le ma", gloss: "have you eaten?" } },
      { id: "shui", glyph: "水", roman: "shuǐ", meaning: "water", anchor: "💧",
        example: { glyph: "一杯水", roman: "yì bēi shuǐ", gloss: "a glass of water" } },
    ],
    tone: {
      title: "Four tones · mā má mǎ mà",
      items: [
        { label: "Tone 1 · high level", glyph: "妈", roman: "mā", gloss: "mother", points: "6,9 58,9" },
        { label: "Tone 2 · rising", glyph: "麻", roman: "má", gloss: "hemp", points: "8,31 56,9" },
        { label: "Tone 3 · dipping", glyph: "马", roman: "mǎ", gloss: "horse", points: "8,15 26,33 56,12" },
        { label: "Tone 4 · falling", glyph: "骂", roman: "mà", gloss: "to scold", points: "8,9 56,31" },
      ],
    },
    vocabulary: [
      { id: "v-nihao", glyph: "你好", roman: "nǐ hǎo", meaning: "hello", deck: "Greetings", anchor: "👋", srs: 5,
        example: { glyph: "你好吗", roman: "nǐ hǎo ma", gloss: "how are you?" } },
      { id: "v-xiexie", glyph: "谢谢", roman: "xiè xie", meaning: "thank you", deck: "Greetings", anchor: "🙏", srs: 4,
        example: { glyph: "谢谢你", roman: "xiè xie nǐ", gloss: "thank you" } },
      { id: "v-zaijian", glyph: "再见", roman: "zài jiàn", meaning: "goodbye", deck: "Greetings", anchor: "👋", srs: 2,
        example: { glyph: "明天见", roman: "míng tiān jiàn", gloss: "see you tomorrow" } },
      { id: "v-duibuqi", glyph: "对不起", roman: "duì bu qǐ", meaning: "sorry", deck: "Greetings", anchor: "🙇", srs: 0,
        example: { glyph: "对不起，我来晚了", roman: "duì bu qǐ, wǒ lái wǎn le", gloss: "sorry I'm late" } },
      { id: "v-cha", glyph: "茶", roman: "chá", meaning: "tea", deck: "Food & drink", anchor: "🍵", srs: 3,
        example: { glyph: "喝茶", roman: "hē chá", gloss: "to drink tea" } },
      { id: "v-shui", glyph: "水", roman: "shuǐ", meaning: "water", deck: "Food & drink", anchor: "💧", srs: 4,
        example: { glyph: "一杯水", roman: "yì bēi shuǐ", gloss: "a glass of water" } },
      { id: "v-mifan", glyph: "米饭", roman: "mǐ fàn", meaning: "cooked rice", deck: "Food & drink", anchor: "🍚", srs: 1,
        example: { glyph: "来一碗米饭", roman: "lái yì wǎn mǐ fàn", gloss: "a bowl of rice, please" } },
      { id: "v-pijiu", glyph: "啤酒", roman: "pí jiǔ", meaning: "beer", deck: "Food & drink", anchor: "🍺", srs: 0,
        example: { glyph: "两瓶啤酒", roman: "liǎng píng pí jiǔ", gloss: "two bottles of beer" } },
      { id: "v-pengyou", glyph: "朋友", roman: "péng you", meaning: "friend", deck: "Daily life", anchor: "🧑‍🤝‍🧑", srs: 2,
        example: { glyph: "好朋友", roman: "hǎo péng you", gloss: "good friend" } },
      { id: "v-gongzuo", glyph: "工作", roman: "gōng zuò", meaning: "work / job", deck: "Daily life", anchor: "💼", srs: 1,
        example: { glyph: "去工作", roman: "qù gōng zuò", gloss: "to go to work" } },
      { id: "v-shijian", glyph: "时间", roman: "shí jiān", meaning: "time", deck: "Daily life", anchor: "🕒", srs: 0,
        example: { glyph: "没有时间", roman: "méi yǒu shí jiān", gloss: "no time" } },
    ],
    converse: {
      scenarios: [
        { id: "tea", label: "Order tea",
          opener: { glyph: "欢迎！你想喝什么？", roman: "huān yíng! nǐ xiǎng hē shén me?", translation: "Welcome! What would you like to drink?" } },
        { id: "neighbor", label: "Greet a neighbor",
          opener: { glyph: "早上好！最近怎么样？", roman: "zǎo shang hǎo! zuì jìn zěn me yàng?", translation: "Good morning! How have you been?" } },
      ],
      suggestions: [
        { glyph: "我想喝茶。", roman: "wǒ xiǎng hē chá.", translation: "I'd like tea." },
        { glyph: "多少钱？", roman: "duō shǎo qián?", translation: "How much is it?" },
        { glyph: "谢谢！", roman: "xiè xie!", translation: "Thank you!" },
      ],
      followups: [
        { glyph: "好的，热的还是冰的？", roman: "hǎo de, rè de hái shì bīng de?", translation: "Sure — hot or iced?" },
        { glyph: "没问题。还要别的吗？", roman: "méi wèn tí. hái yào bié de ma?", translation: "No problem. Anything else?",
          feedback: "Nicely said. Add 请 (qǐng, “please”) before a request to sound more polite." },
        { glyph: "一共二十块，谢谢！", roman: "yí gòng èr shí kuài, xiè xie!", translation: "That's 20 yuan in total, thanks!" },
      ],
    },
  },

  yue: {
    id: "yue",
    pill: "粵",
    name: "Cantonese",
    speechLang: "zh-HK",
    romanSystem: "Jyutping",
    greeting: { glyph: "早晨", roman: "zou2 san4", meaning: "good morning" },
    hero: {
      id: "yue-tea",
      glyph: "茶",
      roman: "caa4",
      meaning: "tea",
      anchor: "🍵",
      example: { glyph: "飲茶", roman: "jam2 caa4", gloss: "to go for dim sum" },
    },
    review: [
      { id: "nei-hou", glyph: "你好", roman: "nei5 hou2", meaning: "hello", anchor: "👋",
        example: { glyph: "你好嗎", roman: "nei5 hou2 maa3", gloss: "how are you?" } },
      { id: "doze", glyph: "多謝", roman: "do1 ze6", meaning: "thank you (for a gift)", anchor: "🙏",
        example: { glyph: "唔該", roman: "m4 goi1", gloss: "thanks / excuse me" } },
      { id: "sikfaan", glyph: "食飯", roman: "sik6 faan6", meaning: "to eat a meal", anchor: "🍚",
        example: { glyph: "食咗飯未", roman: "sik6 zo2 faan6 mei6", gloss: "have you eaten?" } },
      { id: "seoi", glyph: "水", roman: "seoi2", meaning: "water", anchor: "💧",
        example: { glyph: "一杯水", roman: "jat1 bui1 seoi2", gloss: "a glass of water" } },
    ],
    tone: {
      title: "Six tones · si1–si6",
      items: [
        { label: "Tone 1 · high level", glyph: "詩", roman: "si1", gloss: "poem", points: "6,9 58,9" },
        { label: "Tone 2 · high rising", glyph: "史", roman: "si2", gloss: "history", points: "8,27 56,9" },
        { label: "Tone 3 · mid level", glyph: "試", roman: "si3", gloss: "to try", points: "6,20 58,20" },
        { label: "Tone 4 · low falling", glyph: "時", roman: "si4", gloss: "time", points: "8,27 56,34" },
        { label: "Tone 5 · low rising", glyph: "市", roman: "si5", gloss: "market", points: "8,33 56,21" },
        { label: "Tone 6 · low level", glyph: "事", roman: "si6", gloss: "matter", points: "6,31 58,31" },
      ],
    },
    vocabulary: [
      { id: "v-neihou", glyph: "你好", roman: "nei5 hou2", meaning: "hello", deck: "Greetings", anchor: "👋", srs: 5,
        example: { glyph: "你好嗎", roman: "nei5 hou2 maa3", gloss: "how are you?" } },
      { id: "v-zousan", glyph: "早晨", roman: "zou2 san4", meaning: "good morning", deck: "Greetings", anchor: "🌅", srs: 3,
        example: { glyph: "早晨啊", roman: "zou2 san4 aa3", gloss: "morning!" } },
      { id: "v-baaibaai", glyph: "拜拜", roman: "baai1 baai3", meaning: "bye-bye", deck: "Greetings", anchor: "👋", srs: 2,
        example: { glyph: "聽日見", roman: "ting1 jat6 gin3", gloss: "see you tomorrow" } },
      { id: "v-mgoi", glyph: "唔該", roman: "m4 goi1", meaning: "thanks / excuse me", deck: "Greetings", anchor: "🙏", srs: 1,
        example: { glyph: "唔該晒", roman: "m4 goi1 saai3", gloss: "thanks a lot" } },
      { id: "v-caa", glyph: "茶", roman: "caa4", meaning: "tea", deck: "Food & drink", anchor: "🍵", srs: 4,
        example: { glyph: "飲茶", roman: "jam2 caa4", gloss: "to drink tea / yum cha" } },
      { id: "v-seoi", glyph: "水", roman: "seoi2", meaning: "water", deck: "Food & drink", anchor: "💧", srs: 3,
        example: { glyph: "一杯水", roman: "jat1 bui1 seoi2", gloss: "a glass of water" } },
      { id: "v-faan", glyph: "飯", roman: "faan6", meaning: "rice / meal", deck: "Food & drink", anchor: "🍚", srs: 0,
        example: { glyph: "食飯", roman: "sik6 faan6", gloss: "to eat" } },
      { id: "v-bezau", glyph: "啤酒", roman: "be1 zau2", meaning: "beer", deck: "Food & drink", anchor: "🍺", srs: 0,
        example: { glyph: "凍啤", roman: "dung3 be1", gloss: "cold beer" } },
      { id: "v-pangjau", glyph: "朋友", roman: "pang4 jau5", meaning: "friend", deck: "Daily life", anchor: "🧑‍🤝‍🧑", srs: 2,
        example: { glyph: "好朋友", roman: "hou2 pang4 jau5", gloss: "good friend" } },
      { id: "v-faangung", glyph: "返工", roman: "faan1 gung1", meaning: "to go to work", deck: "Daily life", anchor: "💼", srs: 1,
        example: { glyph: "返工喇", roman: "faan1 gung1 laa3", gloss: "off to work" } },
      { id: "v-sigaan", glyph: "時間", roman: "si4 gaan3", meaning: "time", deck: "Daily life", anchor: "🕒", srs: 0,
        example: { glyph: "冇時間", roman: "mou5 si4 gaan3", gloss: "no time" } },
    ],
    converse: {
      scenarios: [
        { id: "tea", label: "Order tea",
          opener: { glyph: "歡迎！想飲啲咩呀？", roman: "fun1 jing4! soeng2 jam2 di1 me1 aa3?", translation: "Welcome! What would you like to drink?" } },
        { id: "neighbor", label: "Greet a neighbor",
          opener: { glyph: "早晨！最近點呀？", roman: "zou2 san4! zeoi3 gan6 dim2 aa3?", translation: "Morning! How have you been lately?" } },
      ],
      suggestions: [
        { glyph: "我想飲茶。", roman: "ngo5 soeng2 jam2 caa4.", translation: "I'd like tea." },
        { glyph: "幾多錢？", roman: "gei2 do1 cin2?", translation: "How much is it?" },
        { glyph: "唔該！", roman: "m4 goi1!", translation: "Thanks!" },
      ],
      followups: [
        { glyph: "好呀,熱定凍？", roman: "hou2 aa3, jit6 ding6 dung3?", translation: "Sure — hot or iced?" },
        { glyph: "冇問題。仲要啲咩？", roman: "mou5 man6 tai4. zung6 jiu3 di1 me1?", translation: "No problem. Anything else?",
          feedback: "Good! In a shop you can add 唔該 (m4 goi1) at the end to be polite." },
        { glyph: "一共二十蚊,唔該！", roman: "jat1 gung6 ji6 sap6 man1, m4 goi1!", translation: "Twenty dollars in total, thanks!" },
      ],
    },
  },

  jpn: {
    id: "jpn",
    pill: "日",
    name: "Japanese",
    speechLang: "ja-JP",
    romanSystem: "Rōmaji",
    greeting: { glyph: "おはよう", roman: "ohayō", meaning: "good morning" },
    hero: {
      id: "jpn-tea",
      glyph: "茶",
      roman: "cha",
      meaning: "tea",
      anchor: "🍵",
      example: { glyph: "お茶", roman: "o-cha", gloss: "(green) tea" },
    },
    review: [
      { id: "konnichiwa", glyph: "こんにちは", roman: "konnichiwa", meaning: "hello / good day", anchor: "👋",
        example: { glyph: "こんばんは", roman: "konbanwa", gloss: "good evening" } },
      { id: "arigatou", glyph: "ありがとう", roman: "arigatō", meaning: "thank you", anchor: "🙏",
        example: { glyph: "どうも", roman: "dōmo", gloss: "thanks" } },
      { id: "taberu", glyph: "食べる", roman: "taberu", meaning: "to eat", anchor: "🍚",
        example: { glyph: "ご飯を食べる", roman: "gohan o taberu", gloss: "to eat a meal" } },
      { id: "mizu", glyph: "水", roman: "mizu", meaning: "water", anchor: "💧",
        example: { glyph: "お水", roman: "o-mizu", gloss: "water (polite)" } },
    ],
    tone: {
      title: "Pitch accent · same kana, different pitch",
      items: [
        { label: "Atamadaka · H→L", glyph: "箸", roman: "hashi", gloss: "chopsticks", points: "8,9 30,9 30,31 56,31" },
        { label: "Heiban · L→H", glyph: "橋", roman: "hashi", gloss: "bridge", points: "8,31 30,11 56,11" },
        { label: "Atamadaka · H→L", glyph: "雨", roman: "ame", gloss: "rain", points: "8,9 30,9 30,31 56,31" },
        { label: "Heiban · L→H", glyph: "飴", roman: "ame", gloss: "candy", points: "8,31 30,11 56,11" },
      ],
    },
    vocabulary: [
      { id: "v-konnichiwa", glyph: "こんにちは", roman: "konnichiwa", meaning: "hello", deck: "Greetings", anchor: "👋", srs: 5,
        example: { glyph: "こんばんは", roman: "konbanwa", gloss: "good evening" } },
      { id: "v-ohayou", glyph: "おはよう", roman: "ohayō", meaning: "good morning", deck: "Greetings", anchor: "🌅", srs: 3,
        example: { glyph: "おはようございます", roman: "ohayō gozaimasu", gloss: "good morning (polite)" } },
      { id: "v-sayounara", glyph: "さようなら", roman: "sayōnara", meaning: "goodbye", deck: "Greetings", anchor: "👋", srs: 1,
        example: { glyph: "またね", roman: "mata ne", gloss: "see you" } },
      { id: "v-arigatou", glyph: "ありがとう", roman: "arigatō", meaning: "thank you", deck: "Greetings", anchor: "🙏", srs: 4,
        example: { glyph: "どうも", roman: "dōmo", gloss: "thanks" } },
      { id: "v-ocha", glyph: "お茶", roman: "o-cha", meaning: "tea", deck: "Food & drink", anchor: "🍵", srs: 3,
        example: { glyph: "お茶をどうぞ", roman: "o-cha o dōzo", gloss: "have some tea" } },
      { id: "v-mizu", glyph: "水", roman: "mizu", meaning: "water", deck: "Food & drink", anchor: "💧", srs: 4,
        example: { glyph: "お水ください", roman: "o-mizu kudasai", gloss: "water, please" } },
      { id: "v-gohan", glyph: "ご飯", roman: "gohan", meaning: "rice / meal", deck: "Food & drink", anchor: "🍚", srs: 1,
        example: { glyph: "ご飯を食べる", roman: "gohan o taberu", gloss: "to eat a meal" } },
      { id: "v-biiru", glyph: "ビール", roman: "bīru", meaning: "beer", deck: "Food & drink", anchor: "🍺", srs: 0,
        example: { glyph: "生ビール", roman: "nama bīru", gloss: "draft beer" } },
      { id: "v-tomodachi", glyph: "友達", roman: "tomodachi", meaning: "friend", deck: "Daily life", anchor: "🧑‍🤝‍🧑", srs: 2,
        example: { glyph: "友達と会う", roman: "tomodachi to au", gloss: "to meet a friend" } },
      { id: "v-shigoto", glyph: "仕事", roman: "shigoto", meaning: "work / job", deck: "Daily life", anchor: "💼", srs: 1,
        example: { glyph: "仕事に行く", roman: "shigoto ni iku", gloss: "to go to work" } },
      { id: "v-jikan", glyph: "時間", roman: "jikan", meaning: "time", deck: "Daily life", anchor: "🕒", srs: 0,
        example: { glyph: "時間がない", roman: "jikan ga nai", gloss: "no time" } },
    ],
    converse: {
      scenarios: [
        { id: "tea", label: "Order tea",
          opener: { glyph: "いらっしゃいませ！お飲み物は？", roman: "irasshaimase! o-nomimono wa?", translation: "Welcome! What would you like to drink?" } },
        { id: "neighbor", label: "Greet a neighbor",
          opener: { glyph: "おはようございます！お元気ですか？", roman: "ohayō gozaimasu! o-genki desu ka?", translation: "Good morning! How are you?" } },
      ],
      suggestions: [
        { glyph: "お茶をください。", roman: "o-cha o kudasai.", translation: "Tea, please." },
        { glyph: "いくらですか？", roman: "ikura desu ka?", translation: "How much is it?" },
        { glyph: "ありがとう！", roman: "arigatō!", translation: "Thank you!" },
      ],
      followups: [
        { glyph: "はい、温かいのと冷たいの、どちらですか？", roman: "hai, atatakai no to tsumetai no, dochira desu ka?", translation: "Sure — hot or cold?" },
        { glyph: "かしこまりました。他には？", roman: "kashikomarimashita. hoka ni wa?", translation: "Certainly. Anything else?",
          feedback: "Great. Ending with です/ます keeps it polite — you did that well." },
        { glyph: "全部で五百円です。ありがとうございます！", roman: "zenbu de gohyaku-en desu. arigatō gozaimasu!", translation: "That's 500 yen in total. Thank you!" },
      ],
    },
  },
};
