import type { LangContent, LangId } from "./types";

export const LANG_ORDER: LangId[] = ["yue", "cmn", "jpn"];
export const TABS = ["Home", "Converse", "Vocabulary", "Reading", "Practice", "Progress"];
export const GOAL_TARGET = 15; // minutes
export const VOCAB_DECKS = ["Greetings", "Food & drink", "Daily life"];

export const CONTENT: Record<LangId, LangContent> = {
  cmn: {
    id: "cmn",
    pill: "普",
    name: "Mandarin",
    speechLang: "zh-CN",
    romanSystem: "Pinyin",
    marks: { reading: "读", practice: "练", progress: "进" },
    greeting: { glyph: "早安", roman: "zǎo ān", meaning: "good morning" },
    hero: {
      id: "cmn-tea",
      glyph: "茶",
      roman: "chá",
      meaning: "tea",
      anchor: "🍵",
      example: { glyph: "喝茶", roman: "hē chá", gloss: "to drink tea" },
    },
    review: [
      { id: "ni-hao", glyph: "你好", roman: "nǐ hǎo", meaning: "hello", anchor: "👋",
        example: { glyph: "你好吗", roman: "nǐ hǎo ma", gloss: "how are you?" } },
      { id: "xiexie", glyph: "谢谢", roman: "xiè xie", meaning: "thank you", anchor: "🙏",
        example: { glyph: "谢谢你", roman: "xiè xie nǐ", gloss: "thank you" } },
      { id: "chifan", glyph: "吃饭", roman: "chī fàn", meaning: "to eat a meal", anchor: "🍚",
        example: { glyph: "吃饭了吗", roman: "chī fàn le ma", gloss: "have you eaten?" } },
      { id: "shui", glyph: "水", roman: "shuǐ", meaning: "water", anchor: "💧",
        example: { glyph: "一杯水", roman: "yì bēi shuǐ", gloss: "a glass of water" } },
    ],
    tone: {
      title: "Four tones · mā má mǎ mà",
      items: [
        { label: "Tone 1 · high level", glyph: "妈", roman: "mā", gloss: "mother", points: "6,9 58,9" },
        { label: "Tone 2 · rising", glyph: "麻", roman: "má", gloss: "hemp", points: "8,31 56,9" },
        { label: "Tone 3 · dipping", glyph: "马", roman: "mǎ", gloss: "horse", points: "8,15 26,33 56,12" },
        { label: "Tone 4 · falling", glyph: "骂", roman: "mà", gloss: "to scold", points: "8,9 56,31" },
      ],
    },
    vocabulary: [
      { id: "v-nihao", glyph: "你好", roman: "nǐ hǎo", meaning: "hello", deck: "Greetings", anchor: "👋", srs: 5,
        example: { glyph: "你好吗", roman: "nǐ hǎo ma", gloss: "how are you?" } },
      { id: "v-xiexie", glyph: "谢谢", roman: "xiè xie", meaning: "thank you", deck: "Greetings", anchor: "🙏", srs: 4,
        example: { glyph: "谢谢你", roman: "xiè xie nǐ", gloss: "thank you" } },
      { id: "v-zaijian", glyph: "再见", roman: "zài jiàn", meaning: "goodbye", deck: "Greetings", anchor: "👋", srs: 2,
        example: { glyph: "明天见", roman: "míng tiān jiàn", gloss: "see you tomorrow" } },
      { id: "v-duibuqi", glyph: "对不起", roman: "duì bu qǐ", meaning: "sorry", deck: "Greetings", anchor: "🙇", srs: 0,
        example: { glyph: "对不起，我来晚了", roman: "duì bu qǐ, wǒ lái wǎn le", gloss: "sorry I'm late" } },
      { id: "v-cha", glyph: "茶", roman: "chá", meaning: "tea", deck: "Food & drink", anchor: "🍵", srs: 3,
        example: { glyph: "喝茶", roman: "hē chá", gloss: "to drink tea" } },
      { id: "v-shui", glyph: "水", roman: "shuǐ", meaning: "water", deck: "Food & drink", anchor: "💧", srs: 4,
        example: { glyph: "一杯水", roman: "yì bēi shuǐ", gloss: "a glass of water" } },
      { id: "v-mifan", glyph: "米饭", roman: "mǐ fàn", meaning: "cooked rice", deck: "Food & drink", anchor: "🍚", srs: 1,
        example: { glyph: "来一碗米饭", roman: "lái yì wǎn mǐ fàn", gloss: "a bowl of rice, please" } },
      { id: "v-pijiu", glyph: "啤酒", roman: "pí jiǔ", meaning: "beer", deck: "Food & drink", anchor: "🍺", srs: 0,
        example: { glyph: "两瓶啤酒", roman: "liǎng píng pí jiǔ", gloss: "two bottles of beer" } },
      { id: "v-pengyou", glyph: "朋友", roman: "péng you", meaning: "friend", deck: "Daily life", anchor: "🧑‍🤝‍🧑", srs: 2,
        example: { glyph: "好朋友", roman: "hǎo péng you", gloss: "good friend" } },
      { id: "v-gongzuo", glyph: "工作", roman: "gōng zuò", meaning: "work / job", deck: "Daily life", anchor: "💼", srs: 1,
        example: { glyph: "去工作", roman: "qù gōng zuò", gloss: "to go to work" } },
      { id: "v-shijian", glyph: "时间", roman: "shí jiān", meaning: "time", deck: "Daily life", anchor: "🕒", srs: 0,
        example: { glyph: "没有时间", roman: "méi yǒu shí jiān", gloss: "no time" } },
    ],
    converse: {
      scenarios: [
        { id: "tea", label: "Order tea",
          opener: { glyph: "欢迎！你想喝什么？", roman: "huān yíng! nǐ xiǎng hē shén me?", translation: "Welcome! What would you like to drink?" } },
        { id: "neighbor", label: "Greet a neighbor",
          opener: { glyph: "早上好！最近怎么样？", roman: "zǎo shang hǎo! zuì jìn zěn me yàng?", translation: "Good morning! How have you been?" } },
      ],
      suggestions: [
        { glyph: "我想喝茶。", roman: "wǒ xiǎng hē chá.", translation: "I'd like tea." },
        { glyph: "多少钱？", roman: "duō shǎo qián?", translation: "How much is it?" },
        { glyph: "谢谢！", roman: "xiè xie!", translation: "Thank you!" },
      ],
      followups: [
        { glyph: "好的，热的还是冰的？", roman: "hǎo de, rè de hái shì bīng de?", translation: "Sure — hot or iced?" },
        { glyph: "没问题。还要别的吗？", roman: "méi wèn tí. hái yào bié de ma?", translation: "No problem. Anything else?",
          feedback: "Nicely said. Add 请 (qǐng, “please”) before a request to sound more polite." },
        { glyph: "一共二十块，谢谢！", roman: "yí gòng èr shí kuài, xiè xie!", translation: "That's 20 yuan in total, thanks!" },
      ],
    },
    reading: {
      passages: [
        { id: "weather", kind: "News", title: { glyph: "今天天气", roman: "jīn tiān tiān qì", translation: "Today's weather" },
          lines: [
            { glyph: "今天天气很好。", roman: "jīn tiān tiān qì hěn hǎo.", translation: "The weather is lovely today." },
            { glyph: "北京有太阳。", roman: "běi jīng yǒu tài yáng.", translation: "It's sunny in Beijing." },
            { glyph: "很多人去公园。", roman: "hěn duō rén qù gōng yuán.", translation: "Lots of people go to the park." },
            { glyph: "他们喝茶，聊天。", roman: "tā men hē chá, liáo tiān.", translation: "They drink tea and chat." },
          ] },
        { id: "cat", kind: "Story", title: { glyph: "小猫和鱼", roman: "xiǎo māo hé yú", translation: "The cat and the fish" },
          lines: [
            { glyph: "小猫很饿。", roman: "xiǎo māo hěn è.", translation: "The kitten is hungry." },
            { glyph: "它看见一条鱼。", roman: "tā kàn jiàn yì tiáo yú.", translation: "It spots a fish." },
            { glyph: "鱼在水里游。", roman: "yú zài shuǐ lǐ yóu.", translation: "The fish swims in the water." },
            { glyph: "小猫等了很久。", roman: "xiǎo māo děng le hěn jiǔ.", translation: "The kitten waited a long time." },
          ] },
        { id: "concert", kind: "News", title: { glyph: "周末活动", roman: "zhōu mò huó dòng", translation: "Weekend activities" },
          lines: [
            { glyph: "这个周末有音乐会。", roman: "zhè ge zhōu mò yǒu yīn yuè huì.", translation: "There is a concert this weekend." },
            { glyph: "很多学生想去。", roman: "hěn duō xué shēng xiǎng qù.", translation: "Many students want to go." },
            { glyph: "票不贵，二十块钱。", roman: "piào bú guì, èr shí kuài qián.", translation: "Tickets aren't expensive — twenty yuan." },
            { glyph: "你也想去吗？", roman: "nǐ yě xiǎng qù ma?", translation: "Do you want to go too?" },
          ],
          question: { ask: "How much is a ticket?", opts: ["二十块 (20 yuan)", "十块 (10 yuan)", "免费 (free)"], a: 0 } },
        { id: "newfriend", kind: "Story", title: { glyph: "新朋友", roman: "xīn péng you", translation: "A new friend" },
          lines: [
            { glyph: "小明今天去学校。", roman: "xiǎo míng jīn tiān qù xué xiào.", translation: "Xiao Ming goes to school today." },
            { glyph: "他认识了一个新同学。", roman: "tā rèn shi le yí ge xīn tóng xué.", translation: "He met a new classmate." },
            { glyph: "他们一起吃午饭。", roman: "tā men yì qǐ chī wǔ fàn.", translation: "They eat lunch together." },
            { glyph: "放学以后一起回家。", roman: "fàng xué yǐ hòu yì qǐ huí jiā.", translation: "After school they walk home together." },
          ],
          question: { ask: "What do they do together?", opts: ["吃午饭 (eat lunch)", "看电影 (watch a film)", "买东西 (go shopping)"], a: 0 } },
        { id: "morning", kind: "News", title: { glyph: "公园的早晨", roman: "gōng yuán de zǎo chén", translation: "Morning in the park" },
          lines: [
            { glyph: "早上公园里很安静。", roman: "zǎo shang gōng yuán lǐ hěn ān jìng.", translation: "The park is very quiet in the morning." },
            { glyph: "老人在树下喝茶。", roman: "lǎo rén zài shù xià hē chá.", translation: "Old people drink tea under the trees." },
            { glyph: "几个孩子在跑步。", roman: "jǐ ge hái zi zài pǎo bù.", translation: "A few children are running." },
            { glyph: "天气慢慢变热了。", roman: "tiān qì màn màn biàn rè le.", translation: "The weather slowly turns warm." },
          ],
          question: { ask: "Where do the old people drink tea?", opts: ["树下 (under the trees)", "家里 (at home)", "学校 (at school)"], a: 0 } },
      ],
    },
    practice: {
      questions: [
        { id: "q1", prompt: "Which character means “tea”?", options: [ { glyph: "茶", correct: true }, { glyph: "水", correct: false }, { glyph: "米", correct: false }, { glyph: "火", correct: false } ] },
        { id: "q2", prompt: "Which means “friend”?", options: [ { glyph: "朋友", correct: true }, { glyph: "工作", correct: false }, { glyph: "时间", correct: false }, { glyph: "谢谢", correct: false } ] },
        { id: "q3", prompt: "Pick the greeting for “hello”.", options: [ { glyph: "你好", correct: true }, { glyph: "再见", correct: false }, { glyph: "对不起", correct: false }, { glyph: "谢谢", correct: false } ] },
        { id: "q4", prompt: "Which means “water”?", options: [ { glyph: "水", correct: true }, { glyph: "茶", correct: false }, { glyph: "饭", correct: false }, { glyph: "酒", correct: false } ] },
      ],
    },
  },

  yue: {
    id: "yue",
    pill: "粵",
    name: "Cantonese",
    speechLang: "zh-HK",
    romanSystem: "Jyutping",
    marks: { reading: "讀", practice: "練", progress: "進" },
    greeting: { glyph: "早晨", roman: "zou2 san4", meaning: "good morning" },
    hero: {
      id: "yue-tea",
      glyph: "茶",
      roman: "caa4",
      meaning: "tea",
      anchor: "🍵",
      example: { glyph: "飲茶", roman: "jam2 caa4", gloss: "to go for dim sum" },
    },
    review: [
      { id: "nei-hou", glyph: "你好", roman: "nei5 hou2", meaning: "hello", anchor: "👋",
        example: { glyph: "你好嗎", roman: "nei5 hou2 maa3", gloss: "how are you?" } },
      { id: "doze", glyph: "多謝", roman: "do1 ze6", meaning: "thank you (for a gift)", anchor: "🙏",
        example: { glyph: "唔該", roman: "m4 goi1", gloss: "thanks / excuse me" } },
      { id: "sikfaan", glyph: "食飯", roman: "sik6 faan6", meaning: "to eat a meal", anchor: "🍚",
        example: { glyph: "食咗飯未", roman: "sik6 zo2 faan6 mei6", gloss: "have you eaten?" } },
      { id: "seoi", glyph: "水", roman: "seoi2", meaning: "water", anchor: "💧",
        example: { glyph: "一杯水", roman: "jat1 bui1 seoi2", gloss: "a glass of water" } },
    ],
    tone: {
      title: "Six tones · si1–si6",
      items: [
        { label: "Tone 1 · high level", glyph: "詩", roman: "si1", gloss: "poem", points: "6,9 58,9" },
        { label: "Tone 2 · high rising", glyph: "史", roman: "si2", gloss: "history", points: "8,27 56,9" },
        { label: "Tone 3 · mid level", glyph: "試", roman: "si3", gloss: "to try", points: "6,20 58,20" },
        { label: "Tone 4 · low falling", glyph: "時", roman: "si4", gloss: "time", points: "8,27 56,34" },
        { label: "Tone 5 · low rising", glyph: "市", roman: "si5", gloss: "market", points: "8,33 56,21" },
        { label: "Tone 6 · low level", glyph: "事", roman: "si6", gloss: "matter", points: "6,31 58,31" },
      ],
    },
    vocabulary: [
      { id: "v-neihou", glyph: "你好", roman: "nei5 hou2", meaning: "hello", deck: "Greetings", anchor: "👋", srs: 5,
        example: { glyph: "你好嗎", roman: "nei5 hou2 maa3", gloss: "how are you?" } },
      { id: "v-zousan", glyph: "早晨", roman: "zou2 san4", meaning: "good morning", deck: "Greetings", anchor: "🌅", srs: 3,
        example: { glyph: "早晨啊", roman: "zou2 san4 aa3", gloss: "morning!" } },
      { id: "v-baaibaai", glyph: "拜拜", roman: "baai1 baai3", meaning: "bye-bye", deck: "Greetings", anchor: "👋", srs: 2,
        example: { glyph: "聽日見", roman: "ting1 jat6 gin3", gloss: "see you tomorrow" } },
      { id: "v-mgoi", glyph: "唔該", roman: "m4 goi1", meaning: "thanks / excuse me", deck: "Greetings", anchor: "🙏", srs: 1,
        example: { glyph: "唔該晒", roman: "m4 goi1 saai3", gloss: "thanks a lot" } },
      { id: "v-caa", glyph: "茶", roman: "caa4", meaning: "tea", deck: "Food & drink", anchor: "🍵", srs: 4,
        example: { glyph: "飲茶", roman: "jam2 caa4", gloss: "to drink tea / yum cha" } },
      { id: "v-seoi", glyph: "水", roman: "seoi2", meaning: "water", deck: "Food & drink", anchor: "💧", srs: 3,
        example: { glyph: "一杯水", roman: "jat1 bui1 seoi2", gloss: "a glass of water" } },
      { id: "v-faan", glyph: "飯", roman: "faan6", meaning: "rice / meal", deck: "Food & drink", anchor: "🍚", srs: 0,
        example: { glyph: "食飯", roman: "sik6 faan6", gloss: "to eat" } },
      { id: "v-bezau", glyph: "啤酒", roman: "be1 zau2", meaning: "beer", deck: "Food & drink", anchor: "🍺", srs: 0,
        example: { glyph: "凍啤", roman: "dung3 be1", gloss: "cold beer" } },
      { id: "v-pangjau", glyph: "朋友", roman: "pang4 jau5", meaning: "friend", deck: "Daily life", anchor: "🧑‍🤝‍🧑", srs: 2,
        example: { glyph: "好朋友", roman: "hou2 pang4 jau5", gloss: "good friend" } },
      { id: "v-faangung", glyph: "返工", roman: "faan1 gung1", meaning: "to go to work", deck: "Daily life", anchor: "💼", srs: 1,
        example: { glyph: "返工喇", roman: "faan1 gung1 laa3", gloss: "off to work" } },
      { id: "v-sigaan", glyph: "時間", roman: "si4 gaan3", meaning: "time", deck: "Daily life", anchor: "🕒", srs: 0,
        example: { glyph: "冇時間", roman: "mou5 si4 gaan3", gloss: "no time" } },
    ],
    converse: {
      scenarios: [
        { id: "tea", label: "Order tea",
          opener: { glyph: "歡迎！想飲啲咩呀？", roman: "fun1 jing4! soeng2 jam2 di1 me1 aa3?", translation: "Welcome! What would you like to drink?" } },
        { id: "neighbor", label: "Greet a neighbor",
          opener: { glyph: "早晨！最近點呀？", roman: "zou2 san4! zeoi3 gan6 dim2 aa3?", translation: "Morning! How have you been lately?" } },
      ],
      suggestions: [
        { glyph: "我想飲茶。", roman: "ngo5 soeng2 jam2 caa4.", translation: "I'd like tea." },
        { glyph: "幾多錢？", roman: "gei2 do1 cin2?", translation: "How much is it?" },
        { glyph: "唔該！", roman: "m4 goi1!", translation: "Thanks!" },
      ],
      followups: [
        { glyph: "好呀,熱定凍？", roman: "hou2 aa3, jit6 ding6 dung3?", translation: "Sure — hot or iced?" },
        { glyph: "冇問題。仲要啲咩？", roman: "mou5 man6 tai4. zung6 jiu3 di1 me1?", translation: "No problem. Anything else?",
          feedback: "Good! In a shop you can add 唔該 (m4 goi1) at the end to be polite." },
        { glyph: "一共二十蚊,唔該！", roman: "jat1 gung6 ji6 sap6 man1, m4 goi1!", translation: "Twenty dollars in total, thanks!" },
      ],
    },
    reading: {
      passages: [
        { id: "weather", kind: "News", title: { glyph: "今日天氣", roman: "gam1 jat6 tin1 hei3", translation: "Today's weather" },
          lines: [
            { glyph: "今日天氣好好。", roman: "gam1 jat6 tin1 hei3 hou2 hou2.", translation: "The weather is great today." },
            { glyph: "香港出太陽。", roman: "hoeng1 gong2 ceot1 taai3 joeng4.", translation: "It's sunny in Hong Kong." },
            { glyph: "好多人去公園。", roman: "hou2 do1 jan4 heoi3 gung1 jyun2.", translation: "Lots of people go to the park." },
            { glyph: "佢哋飲茶傾偈。", roman: "keoi5 dei6 jam2 caa4 king1 gai2.", translation: "They drink tea and chat." },
          ] },
        { id: "cat", kind: "Story", title: { glyph: "貓仔同魚", roman: "maau1 zai2 tung4 jyu2", translation: "The kitten and the fish" },
          lines: [
            { glyph: "貓仔好肚餓。", roman: "maau1 zai2 hou2 tou5 ngo6.", translation: "The kitten is hungry." },
            { glyph: "佢見到一條魚。", roman: "keoi5 gin3 dou2 jat1 tiu4 jyu2.", translation: "It spots a fish." },
            { glyph: "條魚喺水度游。", roman: "tiu4 jyu2 hai2 seoi2 dou6 jau4.", translation: "The fish swims in the water." },
            { glyph: "貓仔等咗好耐。", roman: "maau1 zai2 dang2 zo2 hou2 noi6.", translation: "The kitten waited a long time." },
          ] },
        { id: "concert", kind: "News", title: { glyph: "週末活動", roman: "zau1 mut6 wut6 dung6", translation: "Weekend activities" },
          lines: [
            { glyph: "今個週末有音樂會。", roman: "gam1 go3 zau1 mut6 jau5 jam1 ngok6 wui2.", translation: "There is a concert this weekend." },
            { glyph: "好多學生想去。", roman: "hou2 do1 hok6 saang1 soeng2 heoi3.", translation: "Many students want to go." },
            { glyph: "飛唔貴，二十蚊。", roman: "fei1 m4 gwai3, ji6 sap6 man1.", translation: "Tickets aren't expensive — twenty dollars." },
            { glyph: "你又想唔想去？", roman: "nei5 jau6 soeng2 m4 soeng2 heoi3?", translation: "Do you want to go too?" },
          ],
          question: { ask: "How much is a ticket?", opts: ["二十蚊 ($20)", "十蚊 ($10)", "免費 (free)"], a: 0 } },
        { id: "newfriend", kind: "Story", title: { glyph: "新朋友", roman: "san1 pang4 jau5", translation: "A new friend" },
          lines: [
            { glyph: "小明今日返學。", roman: "siu2 ming4 gam1 jat6 faan1 hok6.", translation: "Siu Ming goes to school today." },
            { glyph: "佢識咗個新同學。", roman: "keoi5 sik1 zo2 go3 san1 tung4 hok6.", translation: "He met a new classmate." },
            { glyph: "佢哋一齊食晏。", roman: "keoi5 dei6 jat1 cai4 sik6 aan3.", translation: "They eat lunch together." },
            { glyph: "放學之後一齊返屋企。", roman: "fong3 hok6 zi1 hau6 jat1 cai4 faan1 uk1 kei2.", translation: "After school they go home together." },
          ],
          question: { ask: "What do they do together?", opts: ["食晏 (eat lunch)", "睇戲 (watch a film)", "買嘢 (go shopping)"], a: 0 } },
        { id: "morning", kind: "News", title: { glyph: "公園嘅朝早", roman: "gung1 jyun2 ge3 ziu1 zou2", translation: "Morning in the park" },
          lines: [
            { glyph: "朝早公園好靜。", roman: "ziu1 zou2 gung1 jyun2 hou2 zing6.", translation: "The park is very quiet in the morning." },
            { glyph: "啲老人喺樹下飲茶。", roman: "di1 lou5 jan4 hai2 syu6 haa6 jam2 caa4.", translation: "Old people drink tea under the trees." },
            { glyph: "幾個細路喺度跑步。", roman: "gei2 go3 sai3 lou6 hai2 dou6 paau2 bou6.", translation: "A few kids are running." },
            { glyph: "天氣慢慢熱起嚟。", roman: "tin1 hei3 maan6 maan2 jit6 hei2 lei4.", translation: "The weather slowly turns warm." },
          ],
          question: { ask: "Where do the old people drink tea?", opts: ["樹下 (under the trees)", "屋企 (at home)", "學校 (at school)"], a: 0 } },
      ],
    },
    practice: {
      questions: [
        { id: "q1", prompt: "Which character means “tea”?", options: [ { glyph: "茶", correct: true }, { glyph: "水", correct: false }, { glyph: "飯", correct: false }, { glyph: "火", correct: false } ] },
        { id: "q2", prompt: "Which means “friend”?", options: [ { glyph: "朋友", correct: true }, { glyph: "返工", correct: false }, { glyph: "時間", correct: false }, { glyph: "多謝", correct: false } ] },
        { id: "q3", prompt: "Pick the greeting for “hello”.", options: [ { glyph: "你好", correct: true }, { glyph: "拜拜", correct: false }, { glyph: "唔該", correct: false }, { glyph: "早晨", correct: false } ] },
        { id: "q4", prompt: "Which means “water”?", options: [ { glyph: "水", correct: true }, { glyph: "茶", correct: false }, { glyph: "飯", correct: false }, { glyph: "啤酒", correct: false } ] },
      ],
    },
  },

  jpn: {
    id: "jpn",
    pill: "日",
    name: "Japanese",
    speechLang: "ja-JP",
    romanSystem: "Rōmaji",
    marks: { reading: "読", practice: "練", progress: "進" },
    greeting: { glyph: "おはよう", roman: "ohayō", meaning: "good morning" },
    hero: {
      id: "jpn-tea",
      glyph: "茶",
      roman: "cha",
      meaning: "tea",
      anchor: "🍵",
      example: { glyph: "お茶", roman: "o-cha", gloss: "(green) tea" },
    },
    review: [
      { id: "konnichiwa", glyph: "こんにちは", roman: "konnichiwa", meaning: "hello / good day", anchor: "👋",
        example: { glyph: "こんばんは", roman: "konbanwa", gloss: "good evening" } },
      { id: "arigatou", glyph: "ありがとう", roman: "arigatō", meaning: "thank you", anchor: "🙏",
        example: { glyph: "どうも", roman: "dōmo", gloss: "thanks" } },
      { id: "taberu", glyph: "食べる", roman: "taberu", meaning: "to eat", anchor: "🍚",
        example: { glyph: "ご飯を食べる", roman: "gohan o taberu", gloss: "to eat a meal" } },
      { id: "mizu", glyph: "水", roman: "mizu", meaning: "water", anchor: "💧",
        example: { glyph: "お水", roman: "o-mizu", gloss: "water (polite)" } },
    ],
    tone: {
      title: "Pitch accent · same kana, different pitch",
      items: [
        { label: "Atamadaka · H→L", glyph: "箸", roman: "hashi", gloss: "chopsticks", points: "8,9 30,9 30,31 56,31" },
        { label: "Heiban · L→H", glyph: "橋", roman: "hashi", gloss: "bridge", points: "8,31 30,11 56,11" },
        { label: "Atamadaka · H→L", glyph: "雨", roman: "ame", gloss: "rain", points: "8,9 30,9 30,31 56,31" },
        { label: "Heiban · L→H", glyph: "飴", roman: "ame", gloss: "candy", points: "8,31 30,11 56,11" },
      ],
    },
    vocabulary: [
      { id: "v-konnichiwa", glyph: "こんにちは", roman: "konnichiwa", meaning: "hello", deck: "Greetings", anchor: "👋", srs: 5,
        example: { glyph: "こんばんは", roman: "konbanwa", gloss: "good evening" } },
      { id: "v-ohayou", glyph: "おはよう", roman: "ohayō", meaning: "good morning", deck: "Greetings", anchor: "🌅", srs: 3,
        example: { glyph: "おはようございます", roman: "ohayō gozaimasu", gloss: "good morning (polite)" } },
      { id: "v-sayounara", glyph: "さようなら", roman: "sayōnara", meaning: "goodbye", deck: "Greetings", anchor: "👋", srs: 1,
        example: { glyph: "またね", roman: "mata ne", gloss: "see you" } },
      { id: "v-arigatou", glyph: "ありがとう", roman: "arigatō", meaning: "thank you", deck: "Greetings", anchor: "🙏", srs: 4,
        example: { glyph: "どうも", roman: "dōmo", gloss: "thanks" } },
      { id: "v-ocha", glyph: "お茶", roman: "o-cha", meaning: "tea", deck: "Food & drink", anchor: "🍵", srs: 3,
        example: { glyph: "お茶をどうぞ", roman: "o-cha o dōzo", gloss: "have some tea" } },
      { id: "v-mizu", glyph: "水", roman: "mizu", meaning: "water", deck: "Food & drink", anchor: "💧", srs: 4,
        example: { glyph: "お水ください", roman: "o-mizu kudasai", gloss: "water, please" } },
      { id: "v-gohan", glyph: "ご飯", roman: "gohan", meaning: "rice / meal", deck: "Food & drink", anchor: "🍚", srs: 1,
        example: { glyph: "ご飯を食べる", roman: "gohan o taberu", gloss: "to eat a meal" } },
      { id: "v-biiru", glyph: "ビール", roman: "bīru", meaning: "beer", deck: "Food & drink", anchor: "🍺", srs: 0,
        example: { glyph: "生ビール", roman: "nama bīru", gloss: "draft beer" } },
      { id: "v-tomodachi", glyph: "友達", roman: "tomodachi", meaning: "friend", deck: "Daily life", anchor: "🧑‍🤝‍🧑", srs: 2,
        example: { glyph: "友達と会う", roman: "tomodachi to au", gloss: "to meet a friend" } },
      { id: "v-shigoto", glyph: "仕事", roman: "shigoto", meaning: "work / job", deck: "Daily life", anchor: "💼", srs: 1,
        example: { glyph: "仕事に行く", roman: "shigoto ni iku", gloss: "to go to work" } },
      { id: "v-jikan", glyph: "時間", roman: "jikan", meaning: "time", deck: "Daily life", anchor: "🕒", srs: 0,
        example: { glyph: "時間がない", roman: "jikan ga nai", gloss: "no time" } },
    ],
    converse: {
      scenarios: [
        { id: "tea", label: "Order tea",
          opener: { glyph: "いらっしゃいませ！お飲み物は？", roman: "irasshaimase! o-nomimono wa?", translation: "Welcome! What would you like to drink?" } },
        { id: "neighbor", label: "Greet a neighbor",
          opener: { glyph: "おはようございます！お元気ですか？", roman: "ohayō gozaimasu! o-genki desu ka?", translation: "Good morning! How are you?" } },
      ],
      suggestions: [
        { glyph: "お茶をください。", roman: "o-cha o kudasai.", translation: "Tea, please." },
        { glyph: "いくらですか？", roman: "ikura desu ka?", translation: "How much is it?" },
        { glyph: "ありがとう！", roman: "arigatō!", translation: "Thank you!" },
      ],
      followups: [
        { glyph: "はい、温かいのと冷たいの、どちらですか？", roman: "hai, atatakai no to tsumetai no, dochira desu ka?", translation: "Sure — hot or cold?" },
        { glyph: "かしこまりました。他には？", roman: "kashikomarimashita. hoka ni wa?", translation: "Certainly. Anything else?",
          feedback: "Great. Ending with です/ます keeps it polite — you did that well." },
        { glyph: "全部で五百円です。ありがとうございます！", roman: "zenbu de gohyaku-en desu. arigatō gozaimasu!", translation: "That's 500 yen in total. Thank you!" },
      ],
    },
    reading: {
      passages: [
        { id: "weather", kind: "News", title: { glyph: "今日の天気", roman: "kyō no tenki", translation: "Today's weather" },
          lines: [
            { glyph: "今日はいい天気です。", roman: "kyō wa ii tenki desu.", translation: "The weather is nice today." },
            { glyph: "東京は晴れです。", roman: "tōkyō wa hare desu.", translation: "It's sunny in Tokyo." },
            { glyph: "多くの人が公園に行きます。", roman: "ōku no hito ga kōen ni ikimasu.", translation: "Many people go to the park." },
            { glyph: "お茶を飲んで話します。", roman: "o-cha o nonde hanashimasu.", translation: "They drink tea and talk." },
          ] },
        { id: "cat", kind: "Story", title: { glyph: "猫と魚", roman: "neko to sakana", translation: "The cat and the fish" },
          lines: [
            { glyph: "猫はお腹がすいています。", roman: "neko wa onaka ga suite imasu.", translation: "The cat is hungry." },
            { glyph: "魚を一匹見つけました。", roman: "sakana o ippiki mitsukemashita.", translation: "It found a fish." },
            { glyph: "魚は水の中を泳ぎます。", roman: "sakana wa mizu no naka o oyogimasu.", translation: "The fish swims in the water." },
            { glyph: "猫は長い間待ちました。", roman: "neko wa nagai aida machimashita.", translation: "The cat waited a long time." },
          ] },
        { id: "concert", kind: "News", title: { glyph: "週末の予定", roman: "shūmatsu no yotei", translation: "Weekend plans" },
          lines: [
            { glyph: "今週末、コンサートがあります。", roman: "konshūmatsu, konsāto ga arimasu.", translation: "There is a concert this weekend." },
            { glyph: "多くの学生が行きたいです。", roman: "ōku no gakusei ga ikitai desu.", translation: "Many students want to go." },
            { glyph: "チケットは安くて、千円です。", roman: "chiketto wa yasukute, sen-en desu.", translation: "Tickets are cheap — 1,000 yen." },
            { glyph: "あなたも行きたいですか。", roman: "anata mo ikitai desu ka.", translation: "Do you want to go too?" },
          ],
          question: { ask: "How much is a ticket?", opts: ["千円 (1,000 yen)", "百円 (100 yen)", "無料 (free)"], a: 0 } },
        { id: "newfriend", kind: "Story", title: { glyph: "新しい友達", roman: "atarashii tomodachi", translation: "A new friend" },
          lines: [
            { glyph: "今日、たけしは学校へ行きます。", roman: "kyō, takeshi wa gakkō e ikimasu.", translation: "Today Takeshi goes to school." },
            { glyph: "新しいクラスメートに会いました。", roman: "atarashii kurasumēto ni aimashita.", translation: "He met a new classmate." },
            { glyph: "一緒に昼ご飯を食べます。", roman: "issho ni hirugohan o tabemasu.", translation: "They eat lunch together." },
            { glyph: "放課後も一緒に帰ります。", roman: "hōkago mo issho ni kaerimasu.", translation: "After school they go home together too." },
          ],
          question: { ask: "What do they do together?", opts: ["昼ご飯を食べる (eat lunch)", "映画を見る (watch a film)", "買い物する (go shopping)"], a: 0 } },
        { id: "morning", kind: "News", title: { glyph: "公園の朝", roman: "kōen no asa", translation: "Morning in the park" },
          lines: [
            { glyph: "朝、公園は静かです。", roman: "asa, kōen wa shizuka desu.", translation: "The park is quiet in the morning." },
            { glyph: "お年寄りが木の下でお茶を飲みます。", roman: "otoshiyori ga ki no shita de o-cha o nomimasu.", translation: "Old people drink tea under the trees." },
            { glyph: "子供たちが走っています。", roman: "kodomo-tachi ga hashitte imasu.", translation: "Children are running." },
            { glyph: "天気はだんだん暑くなります。", roman: "tenki wa dandan atsuku narimasu.", translation: "The weather gradually gets hot." },
          ],
          question: { ask: "Where do the old people drink tea?", opts: ["木の下 (under the trees)", "家 (at home)", "学校 (at school)"], a: 0 } },
      ],
    },
    practice: {
      questions: [
        { id: "q1", prompt: "Which means “tea”?", options: [ { glyph: "お茶", correct: true }, { glyph: "水", correct: false }, { glyph: "ご飯", correct: false }, { glyph: "火", correct: false } ] },
        { id: "q2", prompt: "Which means “friend”?", options: [ { glyph: "友達", correct: true }, { glyph: "仕事", correct: false }, { glyph: "時間", correct: false }, { glyph: "ありがとう", correct: false } ] },
        { id: "q3", prompt: "Pick the greeting for “hello”.", options: [ { glyph: "こんにちは", correct: true }, { glyph: "さようなら", correct: false }, { glyph: "ありがとう", correct: false }, { glyph: "おはよう", correct: false } ] },
        { id: "q4", prompt: "Which means “water”?", options: [ { glyph: "水", correct: true }, { glyph: "お茶", correct: false }, { glyph: "ご飯", correct: false }, { glyph: "ビール", correct: false } ] },
      ],
    },
  },
};
